### ISSUE TITLE
PDF.js v0.7.180 (build: 3699c31) Error: Missing endstream

### ISSUE THREAD

**Issue by Mikka20** [owncloud/apps#1265]
OwnCloud 5.0.9 after uploud a pdf file i get this error when i try to open.

Example pdf files:
http://www.star.bnl.gov/public/daq/HARDWARE/21264_data_sheet.pdf 
https://bugzilla.mozilla.org/attachment.cgi?id=752699

This issue is closed in:
https://github.com/mozilla/pdf.js/issues/2098

PDF.js v0.7.180 (build: 3699c31)
Message: Missing endstream
Stack: Error: Missing endstream
    at error (https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:665:9)
    at Object.Parser_makeStream [as makeStream](https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:30039:9)
    at Object.Parser_getObj [as getObj](https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:29934:18)
    at Object.XRef_fetch [as fetch](https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:4151:22)
    at Object.XRef_fetchIfRef [as fetchIfRef](https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:4103:19)
    at Dict_get [as get](https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:3518:28)
    at Object.PartialEvaluator_getOperatorList [as getOperatorList](https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:14613:30)
    at Object.Page_getOperatorList [as getOperatorList](https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:225:21)
    at Object.wphSetupRenderPage (https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:33464:29)
    at DedicatedWorkerContext.messageHandlerComObjOnMessage (https://ownc/owncloud/apps/files_pdfviewer/3rdparty/pdfjs/pdf.js:33281:19)

**Comment by IdelCoder** [comment]
I also run into this problem. I just open this pdf in the adobe reader, then use "save as" to generate a new file. And it works.
