### ISSUE TITLE
external storage only supports vulnerable SSH servers

### ISSUE THREAD

**Issue by lpirl** [owncloud/apps#2055]
Sadly, I cannot connect to a hardened SSH server since the corresponding library used [does not support recent ciphers/algorithms](https://github.com/phpseclib/phpseclib/issues/676).

### Steps to reproduce
1. harden your SSH server, e.g. according to [this guide](https://stribika.github.io/2015/01/04/secure-secure-shell.html)
2. add it as an external storage

### Expected behaviour
It just works.

### Actual behaviour
The red square is indicating that OC cannot connect.

### Server configuration

**PHP version:** 5.5.0

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** updated

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

**Are you using an external user-backend:** no

#### ownCloud log (data/owncloud.log)
```
{"reqId":"…","remoteAddr":"…","app":"PHP","message":"No compatible key exchange algorithms found at \/var\/www\/vhosts\/example.org\/httpdocs\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SSH2.php#1263","level":3,"time":"2015-05-06T20:26:18+00:00","method":"POST","url":"\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"…","remoteAddr":"…","app":"files_external","message":"Exception: {\"Message\":\"Login failed\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/vhosts\\\/example.org\\\/httpdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/sftp.php(97): OC\\\\Files\\\\Storage\\\\SFTP->getConnection()\
#1 \\\/var\\\/www\\\/vhosts\\\/example.org\\\/httpdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(457): OC\\\\Files\\\\Storage\\\\SFTP->test(false)\
#2 \\\/var\\\/www\\\/vhosts\\\/example.org\\\/httpdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\
#3 \\\/var\\\/www\\\/vhosts\\\/example.org\\\/httpdocs\\\/owncloud\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('SFTP', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, 'user', 'all', false)\
#4 \\\/var\\\/www\\\/vhosts\\\/example.org\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/var\\\/www\\\/vhosts...')\
#5 [internal function]: __lambda_func(Array)\
#6 \\\/var\\\/www\\\/vhosts\\\/example.org\\\/httpdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_310', Array)\
#7 \\\/var\\\/www\\\/vhosts\\\/example.org\\\/httpdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\
#8 \\\/var\\\/www\\\/vhosts\\\/example.org\\\/httpdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\
```

**Comment by MorrisJobke** [comment]
@lpirl Thanks for the report. files_external is one of our core apps. Can I ask you to open this issue in the core repo: https://github.com/owncloud/core/issues Thanks

**Comment by lpirl** [comment]
@MorrisJobke ups, thanks. I expected the app "external" in this repository to be what I was looking for…
