### ISSUE TITLE
CardDav Error at sync with OwnCloud/outlookcaldavsynchronizer

### ISSUE THREAD

**Issue by hegGK** [owncloud/apps#2172]
When using caldavsynchronizer to sync carddav-data with owncloud, I get a 404 error from owncloud.
I reported that to CalDavSynchronizer at got this answer below which suggest a problem in OwnCloud.

The setup:

- hosted Owncloud V9.0.1
- W7 64 Client
- Outlook with CalDavSync 2.1.0.0
- One adressbook in OwnCloud synchronized with one adressbook in outlook

Any help is appreciated.

J. Hergeth

> The server returns a 404-error-response. As far as I know this should not happen, when executing an "addressbook-multiget". The Server should return a DAV:multistatus, which is containing a 404 error.
> IMHO this is a Bug on the server side.
> As a temporary workaround it should help, if you clear the cache of the affected profile.
> br
> Gerhard
> ________________________________________
> [tickets:#289] CardDav Error at sync with OwnCloud
> Status: open
> Milestone: 1.0
> Created: Wed Apr 20, 2016 08:52 AM UTC by Joachim Hergeth
> Last Updated: Wed Apr 20, 2016 08:52 AM UTC
> Owner: nobody
> During synchronisation with an Owncloud server i get the error message below. It is totaly reproducable. I already deleted the profile an created it again. No change.
> Any suggestions?
> J. Hergeth
> ```

### The CalDavSynchronizer error message is:
`<?xml version="1.0" encoding="utf-16"?>
<SynchronizationReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProfileName>Schulkontakte</ProfileName>
  <ProfileId>4d554982-0b68-484d-9519-d7fd391fe818</ProfileId>
  <StartTime>2016-04-22T06:35:43.1677829Z</StartTime>
  <LoadErrors />
  <EntitySynchronizationReports />
  <ExceptionThatLeadToAbortion>CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '404' ('NotFound'). Message:
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"&gt;
  &lt;s:exception&gt;Sabre\DAV\Exception\NotFound&lt;/s:exception&gt;
  &lt;s:message&gt;Card not found&lt;/s:message&gt;
&lt;/d:error&gt;

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;EnsureSuccessStatusCode&gt;d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequest&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.&lt;ExecuteWebDavRequestAndReadResponse&gt;d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CardDavDataAccess.&lt;GetEntities&gt;d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Contacts.CardDavRepository.&lt;Get&gt;d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.Synchronizer`7.EntityContainer.&lt;FillIfEmpty&gt;d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`7.&lt;Synchronize&gt;d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`7.&lt;SynchronizeNoThrow&gt;d__17.MoveNext()</ExceptionThatLeadToAbortion>
  <Duration>00:00:01.8660000</Duration>
</Synchronization>
`

### The Owncloud error message is:
Debug	caldav	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/caldav.php(76): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/html\/owncloud\/remote.php(138): require_once('\/var\/www\/html\/o...')\n#6 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}	2016-04-22T06:52:15+00:00
Debug	caldav	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/caldav.php(76): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/html\/owncloud\/remote.php(138): require_once('\/var\/www\/html\/o...')\n#6 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}
```
```

**Comment by MorrisJobke** [comment]
Please report this in core https://github.com/owncloud/core/issues as the carddav endpoint is maintained in core. Thanks
