### ISSUE TITLE
External storage, google drive broken *update* Readme if not connecting.

### ISSUE THREAD

**Issue by davidleebooth** [owncloud/apps#2189]
### Affected apps
external storage

### Expected behaviour
connect to google drive after granting access with oath2, folder should create 

### Actual behaviour
Tell us what happens instead
oath success, big red square and no folder

### Steps to reproduce
1.  create https install of owncloud and enable external storage app
2. config google drive oath on api console 
3. enter credentials into external drive and grant access

### Server configuration
Operating system:
linux
Web server: 
Apache Version	2.4.23
Database:
MySQL Version	10.0.25-MariaDB-cll-lve
PHP version:
PHP Version	5.6.23
ownCloud version:
8.2.7 stable
### Client configuration
Browser:
chrome
Operating system:
win10
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Error	files_external	Exception: "Creating \OC\Files\Storage\Google storage failed"	2016-07-24T00:51:29+00:00

Error	files_external	Exception: {"Exception":"Exception","Message":"Creating \\OC\\Files\\Storage\\Google storage failed","Code":0,"Trace":"#0 \/home\/davidle1\/public_html\/cloud\/apps\/files_external\/lib\/config.php(258): OC\\Files\\Storage\\Google->__construct(Array)\n#1 \/home\/davidle1\/public_html\/cloud\/apps\/files_external\/controller\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\n#2 \/home\/davidle1\/public_html\/cloud\/apps\/files_external\/controller\/storagescontroller.php(257): OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_external\\Lib\\StorageConfig))\n#3 [internal function]: OCA\\Files_External\\Controller\\StoragesController->show(3)\n#4 \/home\/davidle1\/public_html\/cloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/home\/davidle1\/public_html\/cloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n#6 \/home\/davidle1\/public_html\/cloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\GlobalStoragesController), 'show')\n#7 \/home\/davidle1\/public_html\/cloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('GlobalStoragesC...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#9 \/home\/davidle1\/public_html\/cloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#10 \/home\/davidle1\/public_html\/cloud\/lib\/base.php(853): OC\\Route\\Router->match('\/apps\/files_ext...')\n#11 \/home\/davidle1\/public_html\/cloud\/index.php(39): OC::handleRequest()\n#12 {main}","File":"\/home\/davidle1\/public_html\/cloud\/apps\/files_external\/lib\/google.php","Line":80}	2016-07-24T00:51:25+00:00
```

#### Curl Version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
```

**Comment by RealRancor** [comment]
@davidleebooth Please close here and re-open in:

https://github.com/owncloud/core/issues

The external storage app is located in that repository

**Comment by PVince81** [comment]
Please re-raised in core after retrying with the latest OC versions.

GDrive is known to work so you might want to double check your setup, especially the part in the Google API consoles.
