### ISSUE TITLE
the OS X calendar caldav connection to owncloud 9.1.1 is broken.

### ISSUE THREAD

**Issue by josaladino2** [owncloud/apps#2197]
### Affected apps
Tell us which app(s) you are talking about
Calendar App
### Expected behaviour
Tell us what should happen
I should be able to connect to the oc server via caldav but it is broken and I can't connect
### Actual behaviour
Tell us what happens instead
An error which says that userid or password cannot be verified
### Steps to reproduce
1. Install 9.1.1
2. import a Calendar file which I exported in oc ver 8
3. try to connect and can't - Could not connect to an empty 9.1.1 calendar install

### Server configuration
Operating system: OS X El Capitan latest

Web server: Apache2

Database: MariaDB

PHP version: 7.0

ownCloud version: 9.1.1

### Client configuration
Browser: Google Chrome, Firefox

Operating system: Mac OS x El Capitan

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```Nothing helpful in logs because it does not connect.
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:
{"reqId":"aDl7tKF4k6Q4mBEBLrEm","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_admin\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'nextcloud'@'localhost' for table 'user'","level":3,"time":"2016-09-15T04:22:37+00:00","method":"POST","url":"\/nextcloud\/index.php","user":"--"}
{"reqId":"aDl7tKF4k6Q4mBEBLrEm","remoteAddr":"127.0.0.1","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `nextcloud` . * TO 'nextcloud'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'nextcloud'@'localhost' to database 'nextcloud'","level":3,"time":"2016-09-15T04:22:37+00:00","method":"POST","url":"\/nextcloud\/index.php","user":"--"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"fsockopen(): unable to connect to lastmx.spamexperts.net:585 (Network is unreachable) at \/var\/www\/nextcloud\/apps\/mail\/lib\/service\/autoconfig\/connectivitytester.php#44","level":3,"time":"2016-09-18T11:27:40-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"fsockopen(): unable to connect to mx.spamexperts.com:585 (Connection refused) at \/var\/www\/nextcloud\/apps\/mail\/lib\/service\/autoconfig\/connectivitytester.php#44","level":3,"time":"2016-09-18T11:29:34-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"fsockopen(): unable to connect to fallbackmx.spamexperts.eu:585 (Network is unreachable) at \/var\/www\/nextcloud\/apps\/mail\/lib\/service\/autoconfig\/connectivitytester.php#44","level":3,"time":"2016-09-18T11:31:29-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Uninitialized string offset: 1 at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Smtp\/Horde\/Smtp\/Exception.php#238","level":3,"time":"2016-09-18T11:33:17-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Uninitialized string offset: 1 at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Smtp\/Horde\/Smtp\/Exception.php#238","level":3,"time":"2016-09-18T11:33:23-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"fsockopen(): unable to connect to mx.spamexperts.com:25 (Connection timed out) at \/var\/www\/nextcloud\/apps\/mail\/lib\/service\/autoconfig\/connectivitytester.php#44","level":3,"time":"2016-09-18T11:33:44-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Uninitialized string offset: 1 at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Smtp\/Horde\/Smtp\/Exception.php#238","level":3,"time":"2016-09-18T11:33:49-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Uninitialized string offset: 1 at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Smtp\/Horde\/Smtp\/Exception.php#238","level":3,"time":"2016-09-18T11:33:57-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"fsockopen(): unable to connect to fallbackmx.spamexperts.eu:25 (Connection timed out) at \/var\/www\/nextcloud\/apps\/mail\/lib\/service\/autoconfig\/connectivitytester.php#44","level":3,"time":"2016-09-18T11:34:18-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Uninitialized string offset: 1 at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Smtp\/Horde\/Smtp\/Exception.php#238","level":3,"time":"2016-09-18T11:34:21-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Uninitialized string offset: 1 at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Smtp\/Horde\/Smtp\/Exception.php#238","level":3,"time":"2016-09-18T11:34:25-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Uninitialized string offset: 1 at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Smtp\/Horde\/Smtp\/Exception.php#238","level":3,"time":"2016-09-18T11:34:27-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Uninitialized string offset: 1 at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Smtp\/Horde\/Smtp\/Exception.php#238","level":3,"time":"2016-09-18T11:34:29-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"fsockopen(): unable to connect to lastmx.spamexperts.net:25 (Connection timed out) at \/var\/www\/nextcloud\/apps\/mail\/lib\/service\/autoconfig\/connectivitytester.php#44","level":3,"time":"2016-09-18T11:34:43-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"fsockopen(): unable to connect to bram.net:25 (Connection timed out) at \/var\/www\/nextcloud\/apps\/mail\/lib\/service\/autoconfig\/connectivitytester.php#44","level":3,"time":"2016-09-18T11:35:19-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"oNo+S4t0tO1GC4zVxFO0","remoteAddr":"127.0.0.1","app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 184549104 bytes) at \/var\/www\/nextcloud\/lib\/private\/Security\/Crypto.php#99","level":3,"time":"2016-09-18T11:35:41-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"sMBRaRolJqNYa\/rzec30","remoteAddr":"127.0.0.1","app":"mail","message":"Creating account failed: Error when communicating with the server.","level":3,"time":"2016-09-18T11:49:24-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"ZMAhnmCq\/ueA5jIyqPGK","remoteAddr":"127.0.0.1","app":"mail","message":"Creating account failed: Error connecting to mail server.","level":3,"time":"2016-09-18T11:50:08-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"E1dNNE4cY4d4V1IkaTL4","remoteAddr":"127.0.0.1","app":"mail","message":"Creating account failed: Error when communicating with the server.","level":3,"time":"2016-09-18T11:50:34-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"bB\/\/spCUuKzwrL\/Bs\/BM","remoteAddr":"127.0.0.1","app":"mail","message":"Creating account failed: Server denied authentication.","level":3,"time":"2016-09-18T11:57:03-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"fu0X\/ysO24I3eS1PCyVp","remoteAddr":"127.0.0.1","app":"mail","message":"Creating account failed: Server denied authentication.","level":3,"time":"2016-09-18T11:57:17-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}
{"reqId":"UooNxCs9EWaKEgZVcCZg","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 supported-calendar-component-set must have at least one CALDAV:comp element\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(184): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php\",\"Line\":568,\"User\":\"joe\"}","level":4,"time":"2016-09-18T12:44:40-06:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/dav\/calendars\/joe\/joe-private\/","user":"joe"}
{"reqId":"YeXLcyFlU\/gqC6NtIWtG","remoteAddr":"127.0.0.1","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/owncloud\/lib\/private\/Files\/Filesystem.php:772\nStack trace:\n#0 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(2032): OC\\Files\\Filesystem::normalizePath('\/cissa\/files\/Ph...')\n#1 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(1150): OC\\Files\\View->unlockFile('\/Photos\/Paris.j...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/owncloud\/lib\/private\/Files\/Filesystem.php#772","level":3,"time":"2016-09-18T12:45:27-06:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/theming\/js\/theming?v=0","user":"joe"}
{"reqId":"MT\/7UxOcEuP0oo2BPmBT","remoteAddr":"127.0.0.1","app":"mail","message":"Creating account failed: Error connecting to mail server.","level":3,"time":"2016-09-18T13:07:42-06:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/mail\/accounts","user":"joe"}


a) The javascript console log
b) The network log 
c) ...
```
Here are the links I am working with:
https://i4x.biz/owncloud/remote.php/dav/calendars/test/personal/ <== this works well with Thunderbird.

https://i4x.biz/owncloud/remote.php/dav/principals/users/test/

If this is an Apple problem, then can you let me know what is wrong with the way they build the caldav link to connect to my server?

I have set up a user for you:  test/owncloud

There is one calendar there you should be able to connect to.  It only has one entry in it.

Thanks

Joe Saladino
208-971-7570

**Comment by PVince81** [comment]
Please re-raise in core where the caldav backend is, thanks.

cc @DeepDiver1975
