### ISSUE TITLE
External storage amazon s3 doesn't mount

### ISSUE THREAD

**Issue by MTRichards** [owncloud/apps#54]
Enter all the info for Amazon s3 storage in the app.  Then click on the files page, it loads a blank page.

Error log says:
```
[Sun Oct 28 13:04:39 2012] [error] [client 192.168.149.75] PHP Fatal error:  Uncaught exception 'cURL_Exception' with message 'cURL resource: Resource id #73; cURL error: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed (cURL error code 60). See http://curl.haxx.se/libcurl/c/libcurl-errors.html for an explanation of error codes.' in /srv/www/htdocs/owncloud/3rdparty/aws-sdk/lib/requestcore/requestcore.class.php:824
Stack trace:
#0 /srv/www/htdocs/owncloud/3rdparty/aws-sdk/services/s3.class.php(903): RequestCore->send_request()
#1 /srv/www/htdocs/owncloud/3rdparty/aws-sdk/services/s3.class.php(1624): AmazonS3->authenticate('oc3_test_storag...', Array)
#2 /srv/www/htdocs/owncloud/apps/files_external/lib/amazons3.php(86): AmazonS3->list_objects('oc3_test_storag...', Array)
#3 /srv/www/htdocs/owncloud/lib/filesystemview.php(586): OC_Filestorage_AmazonS3->opendir(false)
#4 /srv/www/htdocs/owncloud/lib/filesystemview.php(173): OC_FilesystemView->basicOperation('opendir', '/AmazonS3/', Array)
#5 in /srv/www/htdocs/owncloud/3rdparty/aws-sdk/lib/requestcore/requestcore.class.php on line 824, referer: http://192.168.149.90/owncloud/settings/admin.php
```

Running SUSE 12.2.

**Comment by cdamken** [comment]
I think this is solved, reopen if needed.
